### ISSUE TITLE
Pass props from presentational component not working. 

### ISSUE THREAD

**Issue by mrmaan4u** [GonzaloCBenlloch/react-router-with-props#1]
I have created a web app for taxi service, I need to pass a value from 1st component to another component via presentational component. I have passed value to presentational compnent using PropsRoute, but not able to pass props from presentational component.

**Comment by GCBenlloch** [comment]
@mrmaan4u Do you mean that you can pass props from the parent to the child with PropsRoute but not from child to parent? Can you share some sample code of what you're trying to achieve?

**Comment by mrmaan4u** [comment]
Actually I was using presentational component as a parent so it wasn't able to pass props, so now I changed it to container component and now it working fine.
Thanks for your quick response, Now I am closing issue.
