### ISSUE TITLE
Redirect from child component to the protected route not working

### ISSUE THREAD

**Issue by grega913** [GonzaloCBenlloch/react-router-with-props#2]
I have router4 part in my main.js component - where there are all the routes  - some are PropsRoutes, and other are Private. Then  I have a Login.js component, where the login process (sending email and verification token ...) is defined. In the case of verified token (from backend), user should be redirected back to the Private Route - which he should be able to access now, since (this.state.authed = true). However, this never happens. I can redirect back to the Public route, but if i try to get to redirect back to one of the PrivateRoutes, (and at this stage the this.state.authed is set to true), the PrivateRoute does not behave as it should - - it gets redirected back to /login page - - not taking in account that authed = true . .

**Comment by grega913** [comment]
This is how the route is defined in main component.     
```
     <PrivateRoute
            exact
            authed={this.state.authed}
            path="/private"
            redirectTo="/login"
            component={DailyNewsForUOnly}
            text="This is a private route"
          />
```

This is how the redirect is set up in Login component:
```
 render() {
    console.log("starting render() function in Login.js");
    console.log("this.state in render() function in Login.js", this.state);
    console.log("this.props in render() function in Login.js", this.props);
    const { from } = this.props.location.state || {
      from: { pathname: "/" }
    };

    const {
      redirectToReferrer,
      loginState,
      requestInMotion,
      loading
    } = this.state;

    console.log("from", from);


    if (redirectToReferrer) {
      return this.renderRedirect(from);
    }

    if (loginState === "verifyToken") {
      return this.renderLoginForm2();
    } else {
      return this.renderLoginForm1();
    }
  }
}
```

**Comment by grega913** [comment]
I see that when redirected path is PrivateRoute - - after Redirecting to it and setting authed in main component to true  - -for some reason the rerendering in my login component happens - - this is the difference in logs if the redirection target is private or public route..

**Comment by GCBenlloch** [comment]
@grega913 Do you redirect immediately after setting the state?

Try defining your login route as public route and letting the router redirect the user itself and let me know if that works

**Comment by grega913** [comment]
I have a redirect part in my Login component - - which is the child of the Main component. Logic is something like this:

1. User navigates to /weeklynews page
2. If this.state.authed in main component is true, then the user should see the weeklynews page
3. if this.state.authed in main component in false, user is redirected to Login page
4. Once in the login page, user write's his email and token, and try to log in.
5. If the response in the login component is OK, the (lifting state up)  - this.props.AuthAfterVerified200() takes care that the state in the main component changes to this.state.authed=true - - this happens through function setAuthToTrue in the main component. At the same time (in login component) render is called to redirect to the /weeklynews - - and I want that at this point the user is redirected and able to get to the /weeklynews page. However - -this is not happening - - for some reason - - I see in console.log - that after SetAuthToTrue function is called - - rerendering happens in login component and user is again at the /login component - - - although this.state.authed is true this time - - and if go to /weeklynews now, it's OK, but the problem is that I should get to the /weeklynews straight after the login is verified - - I hope i'am clear

Thanks for the response.

BTw - I changed the /login route to be Public - - but the behaviour is the same as before

**Comment by grega913** [comment]
I don't know if this is the case but do you think it could be that for some reason this.state.authed in main component gets changed AFTER rerendering happens??

**Comment by GCBenlloch** [comment]
@grega913 I'm pretty sure that's the case, try removing your redirect when using the public route

**Comment by grega913** [comment]
I'm sorry - - could you please be so kind and describe a little bit more what you mean..

**Comment by grega913** [comment]
Because I need this redirect in a first place - - when non authed user gets to the page

**Comment by GCBenlloch** [comment]
In your login route you're making a set state for the parent and a redirect, right?

**Comment by grega913** [comment]
yes

**Comment by GCBenlloch** [comment]
Leave the set state for the parent and remove the redirect, make your login route a PublicRoute so when the new state is set the router will redirect the user

**Comment by grega913** [comment]
It is not helping. Same behaviour - - this is my login route - - no redirect here:

```
      <PublicRoute
            exact
            path="/login"
            component={Login}
            text="Hello world!"
            AuthAfterVerified200={this.setAuthToTrue}
          />

```

**Comment by grega913** [comment]
If I'm making a redirect to  a page, that is public and therefore has no redirect in props - - then it works OK.
However, the whole idea is to get user (once he has inserted valid token and email) to the private page - - and this is not happening

**Comment by grega913** [comment]
{method: "post", url: "https://mysite.com/xxx/auth/verify/", data: {…}, withCredentials: true}
Login.js:139 response from verify {data: "OK", status: 200, statusText: "OK", headers: {…}, config: {…}, …}
Login.js:256 starting render() function in Login.js
Login.js:257 this.state in render() function in Login.js {error: null, email: "sonja.novak55@gmx.com", token: "759757", requestInMotion: false, loginState: "loggedIn", …}
Login.js:258 this.props in render() function in Login.js {match: {…}, location: {…}, history: {…}, staticContext: undefined, exact: true, …}
Login.js:270 from {pathname: "/weeklynews", search: "", hash: "", state: undefined, key: "4knt77"}
Login.js:256 starting render() function in Login.js
Login.js:257 this.state in render() function in Login.js {error: null, email: "sonja.novak55@gmx.com", token: "", requestInMotion: false, loginState: "", …}
Login.js:258 this.props in render() function in Login.js {match: {…}, location: {…}, history: {…}, staticContext: undefined, exact: true, …}
Login.js:270 from {pathname: "/weeklynews", search: "", hash: "", state: undefined, key: "knapu8"}
Main_2.js:46 setAuthToTrue function in Main_2.js
Main_2.js:56 this.state at beginning in Main_2 {authed: true}
Login.js:256 starting render() function in Login.js
Login.js:257 this.state in render() function in Login.js {error: null, email: "sonja.novak55@gmx.com", token: "", requestInMotion: false, loginState: "", …}
Login.js:258 this.props in render() function in Login.js {match: {…}, location: {…}, history: {…}, staticContext: undefined, exact: true, …}
Login.js:270 from {pathname: "/weeklynews", search: "", hash: "", state: undefined, key: "knapu8"}
Login.js:145 this.state at the end of verify {error: null, email: "sonja.novak55@gmx.com", token: "759757", requestInMotion: false, loginState: "loggedIn", …}
Login.js:146 this.props at the end of verify {match: {…}, location: {…}, history: {…}, staticContext: undefined, exact: true, …}

**Comment by grega913** [comment]
this above is the log after receiving 200 from backend . . . when I want redirect to go to the site from where the user has come

this below is the same log . .  .only that this time i am redirecting him (from within my Login component) to a page that is public - - in this case    /public

**Comment by GCBenlloch** [comment]
PublicRoute redirects if the user is authed, I think it's what you're searching for

 https://www.npmjs.com/package/react-router-with-props

**Comment by grega913** [comment]
request to verify
Login.js:133 {method: "post", url: "https://mypage.com/xxx/auth/verify/", data: {…}, withCredentials: true}
Login.js:139 response from verify {data: "OK", status: 200, statusText: "OK", headers: {…}, config: {…}, …}
Login.js:256 starting render() function in Login.js
Login.js:257 this.state in render() function in Login.js {error: null, email: "sonja.novak55@gmx.com", token: "668763", requestInMotion: false, loginState: "loggedIn", …}
Login.js:258 this.props in render() function in Login.js {match: {…}, location: {…}, history: {…}, staticContext: undefined, exact: true, …}
Login.js:270 from {pathname: "/weeklynews", search: "", hash: "", state: undefined, key: "knapu8"}
Main_2.js:46 setAuthToTrue function in Main_2.js
Main_2.js:56 this.state at beginning in Main_2 {authed: true}
Login.js:145 this.state at the end of verify {error: null, email: "sonja.novak55@gmx.com", token: "668763", requestInMotion: false, loginState: "loggedIn", …}
Login.js:146 this.props at the end of verify {match: {…}, location: {…}, history: {…}, staticContext: undefined, exact: true, …}

**Comment by grega913** [comment]
I don't know - - could be I have some errors in login.js - - in a sense I should be using component did mount or similar - - which I am not familiar with . . .

**Comment by GCBenlloch** [comment]
I think you're using wrong the PublicRoute, it need an authed  and a redirectTo prop

**Comment by grega913** [comment]
We are getting somewhere here . .  I've changed my login route part in main2.js to this:
```
          <PublicRoute
            exact
            path="/login"
            authed={this.state.authed}
            redirectTo="/weeklynews"
            component={Login}
            AuthAfterVerified200={this.setAuthToTrue}
          />
```

and this is basically what I want - - if I go through process of login at my Login component - - after successfull login I get redirected to /weeklynews

**Comment by grega913** [comment]
I just need this redirectTo prop to be the one from the whichever page the user got to the login process in the first place

**Comment by GCBenlloch** [comment]
You shouldn't redirect the user, you should set the authed state so the router redirects the user when the new state is set.

Is it working now?

**Comment by grega913** [comment]
?? I am not sure what do you mean by . - you shouldn't redirect the user??

**Comment by GCBenlloch** [comment]
I mean that you should write the redirect inside your component, the router should do it

**Comment by grega913** [comment]
this is last part of my Login component:
```
 renderRedirect(to) {
    return <Redirect to={to} />;
  }

  render() {
    console.log("starting render() function in Login.js");
    console.log("this.state in render() function in Login.js", this.state);
    console.log("this.props in render() function in Login.js", this.props);
    const { from } = this.props.location.state || {
      from: { pathname: "/" }
    };

    const {
      redirectToReferrer,
      loginState,
      requestInMotion,
      loading
    } = this.state;

    console.log("from", from);
    var from1 = "/weeklynews";
    var from2 = "/public";

    if (redirectToReferrer) {
      return this.renderRedirect(from);
    }

    if (loginState === "verifyToken") {
      return this.renderLoginForm2();
    } else {
      return this.renderLoginForm1();
    }
  }
}

export default Login;
```

**Comment by grega913** [comment]
I have defined a renderRedirect function, which holds the redirect command - - >

**Comment by grega913** [comment]
anyway man  - you helped me a great deal . . I got this to behave as I wanted . . thank you a lot
this is the first issue for me on github - - how do I close it?
