### ISSUE TITLE
routeProps.location.pathname

### ISSUE THREAD

**Issue by greenpau** [GonzaloCBenlloch/react-router-with-props#3]
@GCBenlloch , thank you for putting together this repo! :+1: 

* Please confirm that the `from: routeProps.location` needs to be changed to `routeProps.location.pathname`? I am beginner when it comes to React and JS. Perhaps there is some intricacy that I don't understand. It was giving me errors.

https://github.com/GCBenlloch/react-router-with-props/blob/master/src/PrivateRoute.js#L13

* Does the order of attributes/props below need to match the sequence in `PrivateRoute.js`?

README.md:

```
<PrivateRoute exact path="/private" authed={false} redirectTo="/login" component={Title} text="This is a private route"/>
```

`PrivateRoute.js`:

```
const PrivateRoute = ({ component, authed = false, redirectTo, ...rest }) => {
```

* In my case `React.createElement` is somewhat slow, because even when there is no need to render a component, it is still being rendered.

***

The below is simply sharing my experience (documenting in a way :smiley:) ... I discovered this repo when learning about `BrowserRouter` and the need to pass state and dispatches via properties to downstream elements.

Here, the `this.props` contains the props (with state and dispatch actions). 

The chain of components looks roughly like this:

App -> BrowserRouter -> Router via render -> Component

```js
  render() {
    return (
      <BrowserRouter>
      { this.props.checked &&
      <Switch>
        <AuthenticatedRoute component={SignOutScreen} exact path='/signout' {...this.props} />
        <AuthenticatedRoute component={SignedInScreen} exact path='/' {...this.props} />
        <Route exact path='/signin' component={SignInScreen} />
        <Route component={SignInScreen} />
      </Switch>
      }
      </BrowserRouter>
    );
  }

```

For simplicity I shortened the code and left my comments. I learned from your code about the difference between AuthenticatedRoute props and Route props (newbie me), and the need to merge them for the consumption by downstream components :smile:!

```
import React from 'react';
import {Route, Redirect } from 'react-router-dom';
import {Config} from '../../Config';

// The AuthenticatedRoute function handles the creation of components
// The props variable contains the state and props of its parent.
// The routeProps variable container history, location, and match.
const AuthenticatedRoute = ({ component, exact=false, ...props }) => {
    return (
        <Route exact={exact} {...props} render={ (routeProps) => {
            return props.authenticated ? (
                React.createElement(component, Object.assign({}, routeProps, props))
            ) : (
                <Redirect to={{
                    pathname: Config.signInScreen,
                    state: { from: routeProps.location.pathname }
                }}/>
            );
        }}/>
    );
};
```

Thank you, again for this :gem:

**Comment by GCBenlloch** [comment]
Hi @greenpau 

- I pass routerProps.location to have more information available in the children component like the search but probably it's redundant.

- You don't need to pass them in order because it's an object and I'm reconstructing it. You can read more about it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

- I know createElement can be slow but I haven't got time to refactor this package in a long time, maybe I could start in a few weeks

I think with this all your points are answer, thanks very muchs for sharing your experiences and your doubts, this will help improve this repo. I'm closing this issue but fell free to reopen it.
